### ISSUE TITLE
Exception: Method with name FindByInvoiceId

### ISSUE THREAD

**Issue by fernandolopes** [henrique-gouveia/DataQI.Dapper.FastCrud#3]
An exception occurred when I created a method with the name of FindByInvocationId
the probable cause is the IN of the word is conflicting with the IN of the reserved word

**Comment by henrique-gouveia** [comment]
Thank you @fernandolopes, this will resolved in the next version.

**Comment by henrique-gouveia** [comment]
This exception is throws when a property name contains the keyword **_In_**
